modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="wandering_trapper" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Wandering Trapper" #mandatory

credits="Jared for the multiloader framework, ewewukek's musket mod, and the mmd discord" #optional
authors="Lilypure" #optional
description='''
This mod adds a wandering trapper that spawns like the wandering trader, but only in cold biomes.
Unlike the useless wandering trader, the trapper sells various pelts cheaply. You can resell those pelts to a
furrier villager(job block is cake, WIP), who will buy them for much more emeralds. Profit!
You can hunt foxes and polarbears for their pelts. The drop rate is very low, but it gets better as you gain experience.
Be careful when you decide to fight the trapper, he is very strong.
When you install ewewukek's musket mod, he will hold a musket!
'''

[[dependencies.wandering_trapper]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[39,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.wandering_trapper]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.wandering_trapper]]
    modId="musketmod"
    mandatory=false
    versionRange="[1.4.3,)"
    ordering="AFTER"
    side="BOTH"
